<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net48</TargetFramework>
        <OutputType>Library</OutputType>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <LangVersion>latest</LangVersion>
    </PropertyGroup>

    <!-- Debug configuration -->
    <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
        <DebugSymbols>true</DebugSymbols>
        <DebugType>portable</DebugType>
        <Optimize>false</Optimize>
        <OutputPath>..\1.6\Assemblies\</OutputPath>
        <DefineConstants>DEBUG</DefineConstants>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <WarningLevel>4</WarningLevel>
        <Prefer32Bit>false</Prefer32Bit>
    </PropertyGroup>

    <!-- Release configuration -->
    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <DebugType>none</DebugType>
        <Optimize>true</Optimize>
        <OutputPath>..\1.6\Assemblies\</OutputPath>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <WarningLevel>4</WarningLevel>
        <Prefer32Bit>false</Prefer32Bit>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Krafs.Rimworld.Ref" Version="1.6.4633" />
        <PackageReference Include="Lib.Harmony" Version="2.4.2">
            <ExcludeAssets>runtime</ExcludeAssets>
        </PackageReference>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\DevTools\DevTools\DevTools.csproj" />
        <ProjectReference Include="..\Source\PrisonersAreNotSwines.csproj" />
    </ItemGroup>
</Project>